### ISSUE TITLE
最新「BonDriver_BDA-CommonLibs」でビルド出来ない

### ISSUE THREAD

**Issue by fms63v8** [radi-sh/BonDriver_BDA-CommonLibs#1]
１）ビルド環境
　　Win 7 SP1(64bit)
　　VS community 2017 v15.9.21
　　VS community 2019 v16.4.6 / v16.5.0
　　チューナー PX_W3U4

２）ビルド時の問題
　　「Commits on Jan 2, 2020　BonDriver_BDA-CommonLibs」に入れ換えてビルドすると、
　　VS 2017/VS 2019の両方でエラーになりビルド出来ない。
　　error C7525: インライン変数には、最低でも '/std:c++17' が必要です
　　error C2664: 'std::wstring' から 'const WCHAR *' へ変換できません。
　　ビルドログを全て見たわけではないので、他のエラーは分かりません。

　　「Commits on Aug 20, 2019　BonDriver_BDA-CommonLibs」ではVS 2017/VS 2019の
　　両方で正常にビルド出来ます。

３）「/std:c++17」のエラーは「c++言語標準」を変更して解決し、全ビルド数１２個中
　　正常ビルドが３個から７個に増えましたがerror C2664が解決できず、なお５個がエラーなります。
　　正常ビルド：DVBWorld.dll/LWire.dll/PlexPX.dll/TBS.dll/aes.lib/muparser.lib/strmbase.lib

４）何が悪いのかアドバイスを頂けると幸いです。
　　私はプログラムは書けませんが、具体的に「こう書きなさい」と言われれば直す事はできます。

遅くなりましたがradi-shさんのボンドラを長年使用し、PX-W3U4を活用させて頂いています。
どうも有難うございます。

お願い：GitHubはPortableGitでgit cloneしか使用した事がありません。
　　　　なのでこのIssuesでうまくやり取りが出来ず放置状態なった時は
　　　　お手数ですがこのIssuesの削除をお願いします。
　　　　私の方はその旨を下記スレに書き込みますので、よろしくお願いします。
　　　　
　　　　PX-W3U3 Part28【W3U2・S3U2・S3U・W3U4・Q3U4】
　　　　https://mevius.5ch.net/test/read.cgi/avi/1573465788/l50

**Comment by radi-sh** [comment]
「．．．入れ換えてビルドすると、」とありますが、そもそも本体とサブモジュールのバージョンが合致していないのだと思います。
GitHubから本体を取ってくるときに、
git clone --recursive 
を使用してサブモジュールも含めて取得してください。

ここはIssueです。この手の質問は適さないと思われるのでこれでCloseします。
